name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - "master"
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: jfrog.it-academy.by
          username: "sa"
          password: ${{ secrets.JFROG_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins
          push: true
          tags: tags: jfrog.it-academy.by/public/jenkins-ci:zayatsvasiliyv
